### ISSUE TITLE
queued events are dropped in step()?

### ISSUE THREAD

**Issue by rhaschke** [kmarkus/rFSM#8]
If there are several events in the queue, only the one(s) triggering the first (highest prio) transition will be considered. All other events will be dropped silently. What is the rationale behind this?

If events arrive faster than you can process them, i.e. there will be a queue with more than one element,
you will loose some of these events. 

Is this intended behavior?

**Comment by kmarkus** [comment]
It is. Rationale: because a hierarchical FSM is a suitable model to determine what to do given a large number of events. Secondly, because especially in a distributed environment the operation of a system should not depend on whether a single event is received or not. In other words, there should be some robustness built-in to ensure that events are resent or appropriate time triggered transitions defined.

If in specific cases you really want the events to be processed on-by-one, then you are free to implement your own `getevents` hook which returns one event at a time. 

Sorry for the slightly late reply ;-)
